docs: modify the parameter default value problem (#217)
* docs: modify the parameter default value problem

* fix: Solve the problem of TypeError: reactRouter.matchPath is not a function

* Revert "fix: Solve the problem of TypeError: reactRouter.matchPath is not a function"

This reverts commit 0ae4fa0657cd626237344fe1ccf73fb5b72d4236.

Co-authored-by: branhuang <branhuang@tencent.com>